controllers/SettingsController.php
<?php

namespace app\controllers;


use app\behaviors\Access;
use app\models\form\Password;
use app\models\User;
use Yii;
use yii\web\Controller;
use yii\web\UploadedFile;

class SettingsController extends RestController {
    public function behaviors() {
        return [
            'access' => [
                'class' => Access::class,
                'plain' => ['profile', 'wallets', 'password']
            ]
        ];
    }

    public function actionProfile() {
        Access::verifyNick();
        $model = User::findOne(['id' => Yii::$app->user->identity->user]);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $file = UploadedFile::getInstance($model, 'avatar_file');
            if ($file) {
                $nick = Yii::$app->user->identity->nick;
                if ($model->getOldAttribute('avatar')) {
                    $old = Yii::getAlias('@app/web' . $model->getOldAttribute('avatar'));
                    if(file_exists($old)) {
                        unlink($old);
                    }
                }
                $md5 = md5_file($file->tempName);
                header('FILE: ' . $file->tempName);
                header('MD5: ' . $md5);
                $url = "/avatars/$nick-$md5." . $file->getExtension();
                move_uploaded_file($file->tempName, Yii::getAlias('@app/web' . $url));
                $model->avatar = $url;
            }
            $model->save(false);
            Yii::$app->session->setFlash('success', Yii::t('app', 'Successfully'));
        }
        return $this->render('profile', [
            'model' => $model
        ]);
    }

    public function actionWallets() {
        Access::verifyNick();
        $model = User::findOne(['id' => Yii::$app->user->identity->user]);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $can = true;
            foreach (['perfect'] as $name) {
                if (!empty($model->getOldAttribute($name)) && $model->isAttributeChanged($name)) {
                    $model->addError($name, 'Contact technical support for change');
                    $can = false;
                }
            }
            if ($can) {
                $model->save(false);
                Yii::$app->session->setFlash('success', Yii::t('app', 'Successfully'));
            }
        }
        return $this->render('wallets', [
            'model' => $model
        ]);
    }

    public function actionPassword() {
        Access::verifyNick();
        $model = new Password();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = User::findOne(['id' => Yii::$app->user->identity->user]);
            if ($user->validatePassword($model->current)) {
                $user->password = $model->new;
                $user->generateSecret();
                $user->save(false);
                Yii::$app->session->setFlash('success', Yii::t('app', 'Successfully'));
            }
            else {
                $model->addError('current', Yii::t('app', 'Invalid password'));
            }
        }
        return $this->render('password', [
            'model' => $model
        ]);
    }
}

views/settings/password.php
<?php

use app\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = Yii::t('app', 'Password');
?>

<section id="page-password">
    <h1><?= Yii::t('app', 'Password Change') ?></h1>



    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'current')->passwordInput(['maxlength' => 255, 'id' => 'current']) ?>
    <?= $form->field($model, 'new')->passwordInput(['maxlength' => 255, 'id' => 'new']) ?>
    <?= $form->field($model, 'repeat')->passwordInput(['maxlength' => 255, 'id' => 'repeat']) ?>
    <div class="links">
        <?= Html::a('Настройки профиля', ['settings/profile', 'nick' => Yii::$app->user->identity->nick]) ?>
    </div>
    <br>
    <br>
    <?= Html::submitButton(Yii::t('app', 'Change')) ?>
    <?php ActiveForm::end(); ?>
</section>

views/settings/profile.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

$this->title = Yii::t('app', 'Profile');
?>

<section id="page-settings-profile">
    <h1><?= Yii::t('app', 'Change Profile Settings') ?></h1>



    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
    <div>
        <?= $form->field($model, 'forename')
            ->textInput(['maxlength' => 48, 'id' => 'username']) ?>

        <?= $form->field($model, 'surname')
            ->textInput(['maxlength' => 48, 'id' => 'surname']) ?>
    </div>
    <div>
        <?= $form->field($model, 'email')
            ->textInput(['maxlength' => 48, 'id' => 'email']) ?>

        <?= $form->field($model, 'skype')
            ->textInput(['maxlength' => 32, 'id' => 'skype']) ?>
    </div>

    <!-- <div id="upload_avatar">
        <?= $form->field($model, 'avatar_file')
        ->fileInput([
            'accept' => 'image/*'
        ]) ?>
    </div> -->

    <div class="links">
        <?= Html::a('Изменить пароль', ['settings/password', 'nick' => Yii::$app->user->identity->nick]) ?>
    </div>

    <div class="regbutton2">
        <?=
        Html::submitButton(Yii::t('app', 'Save'),
            ['class' => 'width100']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</section>

views/settings/wallets.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

$this->title = Yii::t('app', 'Wallets');
?>

<section id="content">
    <?php require '_breadcrumbs.php' ?>

    <div class="container">
        <div class="section">
            <?php require '_menu.php' ?>

            <div class="row">
                <div class="col s12 m12 l12">
                    <div class="card-panel">
                        <h4 class="header2"><?= Yii::t('app', 'Specify your wallets') ?></h4>
                        <?= Yii::t('app', 'You can change wallets through technical support only') ?>
                        <?php $form = ActiveForm::begin(); ?>

                        <div class="row margin">

                            <?= $form->field($model, 'perfect', [
                                'inputOptions' => ['disabled' => !!$model->perfect, 'class' => 'form-control'],
                                'template' => '
                    <div class="input-field col s6">
                        <i class="mdi-action-lock-outline prefix"></i>{input}{label}{error}{hint}</div>'
                            ])->textInput(['maxlength' => 255, 'id' => 'perfect', 'class' => ''])
                            ?>
                        </div>

                        <!--      <?= $form->field($model, 'perfect',
                            ['inputOptions' => ['disabled' => !!$model->perfect, 'class' => 'form-control']]) ?> -->


                        <div class="row">
                            <div class="input-field col s12">
                                <?= Html::submitButton(Yii::t('app', 'Save') . '<i class="mdi-content-send right"></i>',
                                    ['class' => 'btn cyan waves-effect waves-light right']) ?>
                            </div>
                        </div>

                        <?php ActiveForm::end(); ?>

                        <div class="alert alert-warning" role="alert">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>