models/User.php
<?php

namespace app\models;


use app\helpers\SQL;
use Yii;
use yii\db\ActiveRecord;

/**
 * Class User
 * @property boolean $admin
 * @property integer $id
 * @property integer $parent
 * @property string $nick
 * @property string $surname
 * @property string $forename
 * @property string $email
 * @property string $skype
 * @property string $secret
 * @property string $password
 * @property string $phone
 * @property string $country
 * @property string $settlement
 * @property string $address
 * @property string $blockio
 * @property string $ethereum
 * @package app\models
 */
class User extends ActiveRecord
{
    public $password;
    public $sponsor;
    public $level;
    public $repeat;
    public $avatar_file;

    public function rules() {
        return [
            ['id', 'integer'],
            [['nick', 'email'], 'required'],
            [['surname', 'forename'], 'string', 'min' => 2, 'max' => 48],
            ['nick', 'string', 'min' => 4, 'max' => 24],
            ['nick', 'match', 'pattern' => '/^[a-z][a-z0-9_]+$/i'],
            ['email', 'email'],
            ['ethereum', 'string'],
            [['password', 'repeat'], 'required', 'on' => 'signup'],
            ['repeat', 'compare', 'compareAttribute' => 'password', 'on' => 'signup'],
            ['perfect', 'match', 'pattern' => '/^U\d{7,8}$/', 'message' => 'Format must be U1234567'],
            ['skype', 'match', 'pattern' => '/^[a-zA-Z][a-zA-Z0-9\.,\-_]{5,31}$/'],
            [['surname', 'forename', 'nick', 'email', 'skype', 'perfect', 'sponsor', 'password', 'phone',
                'country', 'settlement', 'address', 'avatar'], 'filter', 'filter' => 'trim'],
            [['surname', 'forename', 'nick', 'email', 'skype', 'perfect', 'sponsor', 'password', 'phone',
                'country', 'settlement', 'address', 'avatar'], 'filter', 'filter' => 'strip_tags'],
            [['surname', 'forename', 'nick', 'email', 'skype', 'perfect', 'sponsor', 'password', 'phone',
                'country', 'settlement', 'address', 'avatar'], 'filter', 'filter' => function ($s) {
                return $s ?: null;
            }],
            [['nick', 'email', 'skype', 'perfect'], 'unique',
                'targetClass' => 'app\models\User',
                'message' => Yii::t('app', 'This value has already been taken')],
            ['sponsor', 'exist',
//                'targetClass' => 'app\models\User',
                'targetAttribute' => 'nick',
                'message' => Yii::t('app', 'Sponsor not found')],
        ];
    }

    public function attributeLabels() {
        return [
            'nick' => Yii::t('app', 'Username'),
            'email' => Yii::t('app', 'Email'),
            'skype' => Yii::t('app', 'Skype'),
            'phone' => Yii::t('app', 'Phone'),
            'forename' => Yii::t('app', 'First Name'),
            'surname' => Yii::t('app', 'Last Name'),
            'perfect' => Yii::t('app', 'Perfect Money'),
            'avatar_file' => Yii::t('app', 'Avatar'),
        ];
    }

    /**
     * @param string $id
     * @return User
     */
    public static function findIdentity($id) {
        return parent::findOne(['id' => $id]);
    }

    public function validatePassword(string $password) {
        return password_verify($password, $this->secret);
    }

    public function generateAuthKey() {
        return $this->generateToken('browser', Yii::$app->security->generateRandomString(24));
    }

    public function generateCode() {
        return $this->generateToken('code', Yii::$app->security->generateRandomString(48));
    }

    public function generateSecret() {
        $this->secret = str_replace('$2y$', '$2a$', password_hash($this->password, PASSWORD_BCRYPT));
    }

    public static function getIdByNick($nick) {
        return static::find()
            ->where(['nick' => $nick])
            ->select(['id'])
            ->one()
            ->id;
    }

    public function generateToken(string $type, $id) {
        if (Yii::$app->db->createCommand()->insert('token', [
            'id' => $id,
            'type' => $type,
            'user' => $this->id,
        ])
            ->execute()
        ) {
            return $id;
        }
        return false;
    }

    public function isAdmin() {
        return $this->admin;
    }

    public function __toString() {
        return $this->nick;
    }

    public function sendEmail($template, $params) {
        $template = Yii::getAlias('@app') . "/mail/$template.php";
        return Yii::$app->mailer->compose()
            ->setTo($this->email)
            ->setFrom(['zbyszek@yopmail.com' => 'admin'])
            ->setSubject($params['subject'])
            ->setHtmlBody(Yii::$app->view->renderFile($template, $params))
            ->send();
    }

    public static function getBalance($currency = 'EUR', $id = null) {
        if (null === $id) {
            $id = Yii::$app->user->identity->user;
        }
        return SQL::scalar('SELECT amount FROM balance WHERE "user" = :id AND currency = :currency', [
            ':id' => $id,
            ':currency' => $currency,
        ]);
    }

    public function canLogin() {
        return true;
//        return Record::find()->andWhere([
//            'object_id' => $this->id,
//            'event' => 'login_fail'
//        ])
//            ->andWhere('time > DATE_SUB(NOW(), INTERVAL 5 MINUTE)')
//            ->count() < 10;
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\behaviors\Access;
use app\helpers\SQL;
use app\models\Email;
use app\models\form\Login;
use app\models\form\PasswordReset;
use app\models\form\RequestPasswordReset;
use app\models\Identity;
use app\models\Log;
use app\models\Token;
use app\models\Transfer;
use app\models\User;
use Yii;
use yii\db\Query;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\ForbiddenHttpException;
use yii\web\Response;

class UserController extends RestController
{
    public function behaviors() {
        return [
            'access' => [
                'class' => Access::class,
                'plain' => ['logout', 'profile'],
                'guest' => ['login', 'signup']
            ]
        ];
    }

    public function beforeAction($action) {
        if ('authorize' === $action->id) {
            Yii::$app->request->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    public function actionSignup() {
        $this->layout = '@app/views/layouts/outdoor';
        $model = new User();
        $model->scenario = 'signup';
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->parent = User::getIdByNick($model->sponsor ?: 'cashladder');
            $model->generateSecret();
            $model->save(false);
            Email::send($model->email, 'Welcome',
                "Dear, $model->nick \nThank you for registration at " . Yii::$app->name);
            $identity = Identity::identifyCookie();
            $identity->login($model->id);
            Yii::$app->user->setIdentity($identity);
            return $this->redirect(['user/profile', 'nick' => $model->nick]);
        } else {
            $sponsor = Yii::$app->request->get('sponsor');
            $model->sponsor = $sponsor ?: 'cashladder';
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionLogin() {
        $this->layout = '@app/views/layouts/outdoor';

        $model = new Login();
        if ($model->load(Yii::$app->request->post())) {
            $user = null;
            if (Login::checkLoginAttempt(['ip' => Yii::$app->request->getUserIP()])) {
                $user = $model->getUser();
                if ($user) {
                    if (Login::checkLoginAttempt(['user' => $user->id])) {
                        if ($user->validatePassword($model->password)) {
                            $identity = Identity::identifyCookie();
                            $identity->login($user->id);
                            Yii::$app->user->setIdentity($identity);
                            Log::log('auth', 'login');
                            return $this->redirect(['user/profile', 'nick' => $user->nick]);
                        } else {
                            $model->addError('password', Yii::t('app', 'Invalid password'));
                        }
                    }
                } else {
                    $model->addError('login', Yii::t('app', 'User does not exists'));
                }
            }
            Log::log('auth', 'invalid', null, $user ? $user->id : null);
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout() {
        Access::verifyNick();
        $id = Yii::$app->user->identity->user;
        Yii::$app->user->identity->logout(null);
        Yii::$app->user->setIdentity(null);
        Log::log('auth', 'logout', null, $id);
        return $this->redirect(['user/login']);
    }

    public function actionProfile($nick) {
        $informer = (new Query())
            ->from('informer')
            ->where(['nick' => $nick])
            ->one();
        $informer = array_merge($informer, Transfer::getFinance($informer['id']));

        if ($informer['parent']) {
            $informer['parent'] = json_decode($informer['parent']);
        }

        return $this->render('profile', [
            'model' => $informer,
            'expires' => SQL::scalar('SELECT max(expires) FROM node'),
            'programs' => [
                1 => 300,
                2 => 500,
                3 => 1500,
                4 => 4100,
                5 => 12000,
                6 => 30000
            ]
        ]);
    }

    public function actionRequest() {
        $this->layout = '@app/views/layouts/outdoor';
        $model = new RequestPasswordReset();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if (($user = $model->getUser())
                && ($code = $user->generateCode())
                && (Email::send($user->email, Yii::t('app', 'Password Recovery'),
                    'You can recover your password ' . Url::to(['user/reset', 'code' => $code], true)))
            ) {
                Yii::$app->session->addFlash('success', Yii::t('app', 'Check your email'));
            } else {
                Yii::$app->session->addFlash('error', Yii::t('app', 'User not found'));
            }
        }
        return $this->render('request', ['model' => $model]);
    }

    public function actionReset($code) {
        $this->layout = '@app/views/layouts/outdoor';
        $model = new PasswordReset();
        $token = Token::findOne(['id' => $code]);
        if ($token) {
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                $user = User::findOne(['id' => $token->user]);
                $user->password = $model->password;
                $user->generateSecret();
                if ($user->save(false) && $token->delete()) {
                    Yii::$app->session->addFlash('success', Yii::t('app', 'Password changed'));
                }
                return $this->redirect(['user/login']);
            }
        } else {
            Yii::$app->session->addFlash('error', Yii::t('app', 'Password recovery code not found'));
//            return $this->redirect(['user/login']);
        }
        return $this->render('reset', ['model' => $model]);
    }

    public function actionAuthorize($nick) {
        if (empty($_REQUEST['token'])) {
            throw new BadRequestHttpException('Token not set');
        }
        $user = User::find()->where(['nick' => $nick])->select(['id', 'nick', 'admin'])->one();
        if ($user) {
            $isAdmin = SQL::scalar('SELECT count(*) FROM identity WHERE admin AND id = :id', ['id' => $_REQUEST['token']]) > 0;
            if ($isAdmin && !$user->admin) {
                Identity::identifyCookie()->login($user->id);
                return $this->redirect(['user/profile', 'nick' => $user->nick]);
            }
            throw new ForbiddenHttpException();
        }
        throw new BadRequestHttpException('User not found');
    }
}

views/user/login.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\form\Login */
/* @var $form ActiveForm */
?>

<section id="page-login" class="section">
    <h1><?= Yii::t('app', 'Login') ?></h1>
    <?php $form = ActiveForm::begin(['options' => ['class' => 'login-form'],]); ?>
    <div class="first">
        <?= $form->field($model, 'login')
            ->textInput([
                'maxlength' => 100,
                'id' => 'username',
                'class' => 'form-control',
                'placeholder' => 'Логин'
            ])
            ->label(false) ?>
        <?= $form->field($model, 'password')
            ->passwordInput([
                'maxlength' => 100,
                'id' => 'password',
                'class' => 'form-control',
                'placeholder' => 'Пароль'
            ])
            ->label(false) ?>
    </div>

    <div>
        <?= Html::a('Забыли пароль?', ['user/request']) ?>
        <?= Html::submitButton(Yii::t('app', 'Login'),
            ['class' => 'button full-width']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</section>

views/user/password.php
<?php

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\form\Password
 * @var $form ActiveForm
 */

$reset = !$model || 'reset' == $model->scenario;
$this->title = Yii::t("app", $reset ? 'Reset Password' : 'Set Password');

if ($message): ?>
    <div class="alert alert-danger"><?= $message ?></div>
<?php else: ?>
    <article class="section" id="page-password" class="<?= $reset ? 'reset-password' : 'set-password' ?>">
        <h1><?= $this->title ?></h1>
        <?php $form = ActiveForm::begin(); ?>

        <?php if (!$reset) {
            echo $form->field($model, 'password')->passwordInput();
        } ?>
        <?= $form->field($model, 'new_password')->passwordInput() ?>
        <?= $form->field($model, 'repeat_password')->passwordInput() ?>

        <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-primary']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </article>
<?php
endif;

views/user/profile.php
<?php
use app\helpers\Html;
use yii\helpers\Url;

/* @var $model array */

$profileData = json_encode($model);
echo Html::script("const userProfile = $profileData;");

extract($model);

$referral = Url::to(['user/signup', 'sponsor' => $nick], true);

$isMe = Yii::$app->user->getIsGuest() ? false : Yii::$app->user->identity->nick === $nick;
?>

<article id="page-profile" xmlns:v-bind="http://www.w3.org/1999/xhtml">
    <section class="">
        <ul>
            <li>
                <span>Логин:</span>
                <span><?= $nick ?></span>
            </li>
            <?php if (!empty($parent)): ?>
                <li>
                    <span>Спонсор:</span>
                    <span><?= $parent->nick ?></span>
                </li>
            <?php endif; ?>
            <li>
                <span>Баланс:</span>
                <span><?= Html::money($balance) ?></span>
            </li>
            <li>
                <span>Парт. ссылка:</span>
                <?= Html::textInput('reflink', $referral) ?>
            </li>
        </ul>
    </section>
    <section class="days">
        <div v-if="days >= 0">
            <div class="text">Осталось дней до покупки: {{ days }}</div>
            <input type="hidden" name="expires" value="<?= $expires ?>"/>
            <div class="list">
                <?php
                foreach (range(1, 7) as $number):
                    $day = strtotime($expires) + $number * 24 * 3600;
                    ?>
                    <div data-expires="<?= $day ?>"
                         v-bind:class="{
                         day: true,
                         <?= $number ?>: true,
                         available: <?= $day > time() ? 'true' : 'false' ?>
                     }">
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div v-else>
            <div>Нет активных покупок</div>
        </div>
    </section>
    <section class="programs">
        <h2>Тарифы</h2>
        <div>
            <?php foreach ($programs as $id => $price): ?>
                <?= Html::beginTag('a', [
                    'style' => ['margin-top' => 360 - $id * 60],
                    'href' => Url::to(['program/index',
                        'id' => $id,
                        'nick' => Yii::$app->user->identity->nick
                    ])
                ]) ?>
                <img src="/images/<?= $id ?>.png">
                <div>
                    <div class="h-stupen">Ступень <?= $id ?></div>
                    <div class="eur"><?= $price ?></div>
                </div>
                <?= Html::endTag('a') ?>
            <?php endforeach; ?>
        </div>
    </section>
</article>

views/user/request.php
<?php

use yii\bootstrap\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\form\RequestPasswordReset
 * @var $form ActiveForm
 */

$this->title = Yii::t('app', 'Password Recovery Request');
?>

<section id="page-request" class="section">
    <?php $form = ActiveForm::begin(); ?>
    <h1><?= Yii::t('app', 'Reset password') ?></h1>

    <?= $form->field($model, 'email')->textInput([
        'maxlength' => 100,
        'id' => 'email',
        'placeholder' => 'Email'
    ]) ?>
    
    <div class="regbutton">
        <?= Html::submitButton(Yii::t('app', 'Send Email'),
            ['class' => 'button full-width']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</section>

views/user/reset.php
<?php

use yii\bootstrap\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\form\RequestPasswordReset
 * @var $form ActiveForm
 */

$this->title = Yii::t('app', 'Password Recovery');

?>

<section id="page-reset">
    <h1><?= Yii::t('app', 'Reset password') ?></h1>
    <?php $form = ActiveForm::begin([
        'enableClientValidation' => false,
        'enableAjaxValidation' => false,
    ]); ?>

    <?= $form->field($model, 'password')->passwordInput([
        'maxlength' => 100,
        'id' => 'password',
        'placeholder' => 'Пароль'
    ]) ?>
    <?= $form->field($model, 'repeat')->passwordInput([
        'maxlength' => 100,
        'id' => 'repeat',
        'placeholder' => 'Повторите пароль'
    ]) ?>

    <div>
        <?= Html::submitButton(Yii::t('app', 'Reset'),
            ['class' => 'button full-width']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</section>

views/user/signup.php
<?php

use yii\bootstrap\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<article id="page-signup" class="section">
    <?php $form = ActiveForm::begin([
        'enableClientValidation' => false,
        'enableAjaxValidation' => false
    ]); ?>
    <h1><?= Yii::t('app', 'Create an account') ?></h1>

    <div class="pair">
        <?= $form->field($model, 'forename')->textInput([
            'maxlength' => 48,
            'id' => 'forename',
            'placeholder' => 'Имя'
        ]) ?>
        <?= $form->field($model, 'surname')->textInput([
            'maxlength' => 48,
            'id' => 'surname',
            'placeholder' => 'Фамилия'
        ]) ?>
    </div>
    <div class="pair">
        <?= $form->field($model, 'nick')->textInput([
            'maxlength' => 24,
            'id' => 'username',
            'placeholder' => 'Логин'
        ]) ?>
        <?= $form->field($model, 'sponsor')->textInput([
            'maxlength' => 24,
            'id' => 'sponsor',
            'placeholder' => 'Спонсор'
        ]) ?>
    </div>
    <div class="pair">
        <?= $form->field($model, 'password')->passwordInput([
            'maxlength' => 100,
            'id' => 'password',
            'placeholder' => 'Пароль'
        ]) ?>
        <?= $form->field($model, 'repeat')->passwordInput([
            'maxlength' => 100,
            'id' => 'repeat',
            'placeholder' => 'Повторите пароль'
        ]) ?>
    </div>
    <div class="pair">
        <?= $form->field($model, 'email')->textInput([
            'maxlength' => 64,
            'id' => 'email',
            'placeholder' => 'Email'
        ]) ?>
        <?= $form->field($model, 'skype')->textInput([
            'maxlength' => 32,
            'id' => 'skype',
            'placeholder' => 'Skype'
        ]) ?>
    </div>

    <div class="regbutton">
        <label>
            <input type="checkbox" required/>
            я знаком и согласен с
            <?= Html::a('правилами', '/rules') ?>
        </label>
        <br/>
        <?= Html::submitButton(Yii::t('app', 'Signup'),
            ['class' => 'button full-width']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</article>