models/Transfer.php
<?php

namespace app\models;


use app\helpers\SQL;
use Yii;
use yii\db\ActiveRecord;
use yii\db\mssql\PDO;
use yii\db\Query;

/**
 * Class Transfer
 * @property integer $id
 * @property integer $from
 * @property integer $to
 * @property integer $amount
 * @property string $type
 * @property string $status
 * @property integer $node
 * @property string $text
 * @property string $wallet
 * @property string $txid
 * @property string $ip
 * @property string $created
 * @property string $time
 * @package app\models
 */
class Transfer extends ActiveRecord
{
    public static $systems = [
        'perfect' => 'Perfect Money',
        'payeer' => 'Payeer',
        'advcash' => 'AdvCash',
    ];

    public static $currencies = [
        'perfect' => 'EUR',
        'advcash' => 'EUR',
        'ethereum' => 'EUR',
    ];

    public static $types = ['buy', 'payment', 'withdraw', 'accrue', 'bonus'];

    public function rules() {
        return [
            ['from', 'integer'],
            ['to', 'integer'],
            ['amount', 'integer'],
            ['type', 'string'],
            ['status', 'string'],
            ['node', 'integer'],
            ['text', 'string'],
            ['wallet', 'string'],
            ['txid', 'string'],
            ['ip', 'string'],
            ['created', 'datetime'],
            ['time', 'string'],
        ];
    }

    public function attributeLabels() {
        return [
            'status' => Yii::t('app', 'Operation'),
            'created' => Yii::t('app', 'Time'),
            'amount' => Yii::t('app', 'Amount'),
            'type' => Yii::t('app', 'Type'),
            'text' => Yii::t('app', 'Comment'),
            'user' => Yii::t('app', 'User'),
        ];
    }

    public static function keyBy($rows, $key = 'currency') {
        $result = [];
        foreach ($rows as $row) {
            $result[$row[$key]] = $row['amount'];
        }
        return $result;
    }

    public static function getFinance($user) {
        $rows = (new Query())->from('finance')
            ->where(['user' => $user])
            ->select(['type', 'currency', 'amount'])
            ->all();
        $finance = [];
        $additional = ['balance'];
//        $additional = ['balance', 'turnover', 'daily'];
        foreach (array_merge($additional, static::$types) as $type) {
            $finance[$type] = [];
            foreach (array_values(static::$currencies) as $currency) {
                $finance[$type][$currency] = 0;
            }
        }
        foreach ($rows as $row) {
            $finance[$row['type']][$row['currency']] = $row['amount'];
        }
        foreach ($additional as $key) {
            $amount = SQL::queryAll("SELECT currency, amount FROM $key WHERE \"user\" = :user",
                [':user' => $user], PDO::FETCH_KEY_PAIR);
            if ($amount) {
                $finance[$key] = $amount;
            }
        }
        return $finance;
    }

    public static function getExchange() {
        return ['EUR' => ['EUR' => 100]];
    }

    public function getDescription() {
        if ($this->text) {
            if ($this->vars) {
                return Yii::t("app", $this->text, json_decode($this->vars, JSON_OBJECT_AS_ARRAY));
            }
            return Yii::t("app", $this->text);
        }
        switch ($this->type) {
            case 'payment':
                return Yii::t('app', 'Payment from {wallet}', ['wallet' => $this->wallet]);
            case 'withdraw':
                return Yii::t('app', 'Withdrawal to {wallet}', ['wallet' => $this->wallet]);
            case 'support':
                return Yii::t('app', 'Administrative');
            default:
                return $this->type;
        }
    }

    public static function getTicker() {
        $texts = [];
        foreach (Transfer::find()->limit(10)->all() as $t) {
            $texts[] = $t->getDescription();
        }
        return $texts;
    }
}

controllers/TransferController.php
<?php

namespace app\controllers;


use app\behaviors\Access;
use app\helpers\SQL;
use app\helpers\Utils;
use app\models\form\Payment;
use app\models\form\Withdraw;
use app\models\Log;
use app\models\Transfer;
use app\models\User;
use PDO;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\web\Response;

class TransferController extends RestController
{
    public function behaviors() {
        return [
            'access' => [
                'class' => Access::class,
                'plain' => ['index', 'pay', 'withdraw', 'address']
            ]
        ];
    }

    public function beforeAction($action) {
//        Access::verifyNick();
        return parent::beforeAction($action);
    }

    public function actionIndex() {
        $user = Yii::$app->user->identity->user;
        $query = Transfer::find()
            ->where(['or', ['from' => $user], ['to' => $user]])
            ->andFilterWhere(Utils::pick($_GET, ['currency', 'type']));
        $provider = new ActiveDataProvider([
            'query' => $query
        ]);

        $amount = Yii::$app->request->get('amount');
        $payment = new Payment();
        if ($amount) {
            $payment->amount = $amount / 100;
        }
        if ($payment->load(Yii::$app->request->post()) && $payment->validate()) {
            return $this->redirect([$payment->system . '/pay', 'amount' => $payment->amount * 100]);
        }

        return $this->render('index', [
            'payment' => $payment,
            'provider' => $provider,
            'ticker' => Transfer::getTicker()
        ]);
    }

    public function actionIncome() {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $user = Yii::$app->user->identity->user;
        $transfers = SQL::queryAll('SELECT * FROM transfer WHERE "to" = :user AND type = \'accrue\' ORDER BY id DESC LIMIT 6',
            [':user' => $user]);
        return ['result' => $transfers];
    }

    public function actionWithdraw() {
        $user_id = Yii::$app->user->identity->user;
        $transfer = Transfer::findOne([
            'from' => $user_id,
            'type' => 'withdraw',
            'status' => 'created'
        ]);
        if ($transfer) {
            Yii::$app->session->setFlash('error',
                Yii::t('app', 'You cannot create more than one withdrawal request'));
            Log::log('withdraw', 'second');
            return $this->redirect(['transfer/index', 'id' => $transfer->id]);
        }
        $model = new Withdraw();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $amount = $model->amount * 100;
            $t = Yii::$app->db->beginTransaction();
            $currency = Transfer::$currencies[$model->system];
            $min = Withdraw::$minimal[$currency];
//            header('H:' . $currency . $min);
            if ($amount >= $min) {
                $balance = User::getBalance($currency);
                if ($balance - $amount >= 0) {
                    $transfer = new Transfer([
                        'type' => 'withdraw',
                        'status' => 'created',
                        'currency' => $currency,
                        'from' => $user_id,
                        'amount' => $amount,
                        'wallet' => $model->wallet,
                        'text' => empty($model->text) ? null : $model->text
                    ]);
                    if ($transfer->save(false)) {
                        $commission = SQL::scalar('SELECT amount FROM need_commission WHERE "user" = :user', [
                            ':user' => $user_id
                        ]);
                        if ($commission > 0) {
                            $c = new Transfer([
                                'type' => 'commission',
                                'status' => 'success',
                                'currency' => $currency,
                                'from' => $user_id,
                                'amount' => $commission,
                                'vars' => json_encode(['withdraw' => $transfer->id]),
                                'text' => empty($model->text) ? null : $model->text
                            ]);
                            $c->save(false);
                        }
                        Yii::$app->session->setFlash('success',
                            Yii::t('app', 'Withdrawal request created'));
                        $t->commit();
                        return $this->redirect(['transfer/index', 'id' => $transfer->id]);
                    }
                } else {
                    Log::log('withdraw', 'insufficient', [
                        'balance' => $balance,
                        'amount' => $amount,
                        'wallet' => $model->wallet,
                        'currency' => $currency
                    ]);
                    $model->addError('amount', Yii::t('app', 'Insufficient funds'));
                }
                $t->rollBack();
            } else {
                $model->addError('amount', Yii::t('app', 'Minimal amount is {amount}', [
                    'amount' => '0.01 ETH'
                ]));
            }
        }
        return $this->render('withdraw', [
            'model' => $model
        ]);
    }

    public function actionHistogram($user, $types, $start, $currencies = 'USD', $step = '1 day', $stop) {
        Yii::$app->response->format = Response::FORMAT_JSON;
//        Yii::$app->response->headers->add('Cache-Control', 'max-age=3600, public');
        $types = explode(',', $types);
        $currencies = explode(',', $currencies);
        $params = [
            ':start' => $start,
            ':step' => $step,
            ':user' => $user,
            ':stop' => $stop
        ];
        $many = function ($array) use (&$params) {
            $pp = [];
            foreach ($array as $el) {
                $p = ':p' . count($params);
                $params[$p] = $el;
                $pp[] = $p;
            }
            return implode(',', $pp);
        };

        $pType = $many($types);
        $pCurrencies = $many($currencies);

        $histogram = SQL::queryAll("SELECT
        currency,
        type,
        s AS time,
        sum(coalesce(amount, 0)) AS amount
  FROM generate_series(:start::TIMESTAMP, :stop::TIMESTAMP, :step::INTERVAL) s LEFT JOIN user_transfer t
      ON
        t.created >= s
        AND t.created < s + :step::INTERVAL
        AND currency IN ($pCurrencies)
        AND type IN ($pType)
        AND \"user\" = :user
  GROUP BY s, type, currency ORDER BY time", $params);
        $result = [];
        foreach ($histogram as $m) {
            $time = $m['time'];
            if (!isset($result[$time])) {
                $result[$time] = [];
            }
            if (null !== $m['currency']) {
                unset($m['time']);
                $result[$time][] = $m;
            }
        }
        // Remove invalid data
//        array_pop($result);
        return ['result' => $result];
    }
}

views/transfer/autosubmit.php
<?php
use app\helpers\Html;

?>

<form action="<?= $url ?>" method="POST" class="autosubmit section">
    <?= Html::tag('h1', Yii::t('app', 'Wait please...')) ?>
    <?php
    foreach ($data as $name => $value) {
        echo Html::hiddenInput($name, $value);
    }
    ?>
</form>

views/transfer/index.php
<?php
use app\helpers\Html;
use app\models\Transfer;
use yii\grid\GridView;
use yii\widgets\ActiveForm;

$focus = empty($_GET['id']) ? null : +$_GET['id'];
$nick = Yii::$app->user->identity->nick;

function param($key, $value = null, $text = null) {
    $params = $_GET;
    if ($value) {
        $params[$key] = $value;
    } else {
        unset($params[$key]);
    }
    $params[0] = 'transfer/index';
    return Html::a(Yii::t("app", $text) ?: $value, $params);
}

function params($label, $key, $values) {
    $result = [param($key, null, 'All')];
    foreach ($values as $value => $text) {
        $result[] = param($key, is_numeric($value) ? $text : $value, $text);
    }
    return Html::tag('span',
        Html::tag('span', Yii::t("app", $label), ['class' => 'label'])
        . Html::tag('span', implode(' | ', $result), ['class' => 'values ' . $key]), [
            'id' => 'filter-' . $key
        ]);
}

/**
 * @var yii\data\ArrayDataProvider $provider
 */
?>
<article id="page-transfers" class="section">
    <h1>Мои финансы</h1>

    <div class="ticker">
        <?php
        for ($i = 0; $i < count($ticker); $i++) {
            $text = $ticker[$i];
            echo "<div v-bind:class=\"{active: $i === ticker}\">$text</div>";
        }
        ?>
    </div>

    <?php $form = ActiveForm::begin(['id' => 'form-payment']) ?>
    <?= $form->field($payment, 'amount')
        ->textInput(['placeholder' => 'Сумма'])
        ->label('Пополнение') ?>
    <div>
        <?= $form
            ->field($payment, 'system')
            ->hiddenInput(['v-model' => 'system'])
            ->label(false) ?>

        <?php foreach (Transfer::$systems as $id => $name): ?>
            <?= Html::button($name, ['name' => $id, 'v-on:click' => "pay('$id')"]) ?>
        <?php endforeach; ?>
        <?= Html::a('Withdraw', ['transfer/withdraw']) ?>
    </div>
    <?php ActiveForm::end() ?>
</article>
<article id="page-transfers" class="section">
    <!--    <?= params('Type: ', 'type', [
        'payment' => 'Payment',
        'withdraw' => 'Withdrawn',
        'accrue' => 'Accruals',
        'bonus' => 'Referral',
    ]) ?> -->

    <?= Yii::t('app', 'Payment from {wallet}', ['wallet' => 'abc']) ?>

    <?= GridView::widget([
        'dataProvider' => $provider,
        'layout' => '<div class="table-control2">{errors}</div>{items}{summary}{pager}',
        'tableOptions' => ['class' => 'striped bordered'],
        'emptyText' => 'Nothing found',
        'rowOptions' => function (Transfer $model) use ($focus) {
            $class = $focus === $model->id ? 'focus' : 'normal';
            return ['class' => $class];
        },
        'columns' => [
            'id',
            [
                'attribute' => 'created',
                'label' => Yii::t('app', 'Time'),
                'format' => 'datetime',
                'contentOptions' => function (Transfer $model) {
                    return ['data-time' => strtotime($model->created)];
                }
            ],
            [
                'attribute' => 'amount',
                'format' => 'html',
                'value' => function (Transfer $model) {
                    $sign = $model->to === Yii::$app->user->identity->user ? '+' : '-';
                    $currency = strtolower($model->currency);
                    return "<span class=\"sign\">$sign</span><span class=\"$currency\">$model->amount</span>";
                }
            ],
            [
                'attribute' => 'text',
                'label' => Yii::t('app', 'Description'),
                'value' => function (Transfer $model) {
                    return $model->getDescription();
                }
            ],
            [
                'attribute' => 'status',
                'label' => Yii::t('app', 'Status'),
                'value' => function (Transfer $model) {
                    switch ($model->status) {
                        case 'success':
                            return "\u{2713}";

                        case 'fail':
                            return "\u{274C}";

                        case 'canceled':
                            return "Canceled";

                        case 'created':
                            return 'Created';
                        default:
                            return $model->status;
                    }
                }
            ],
        ]
    ]) ?>
</article>

views/transfer/withdraw.php
<?php
use app\models\Transfer;
use yii\widgets\ActiveForm;
?>

<section class="section transfer-withdraw">
    <?php $form = ActiveForm::begin() ?>
    <?= $form->field($model, 'system')->dropDownList(Transfer::$systems) ?>
    <?= $form->field($model, 'amount')->textInput(['maxlength' => 12, 'id' => 'amount']) ?>
    <?= $form->field($model, 'wallet')->textInput(['maxlength' => 128, 'id' => 'wallet']) ?>
    <?= $form->field($model, 'text')->textInput(['maxlength' => 255, 'id' => 'text']) ?>

    <button type="submit" class="btn btn-success">
        <?= Yii::t('app', 'Create') ?>
    </button>
    <?php ActiveForm::end() ?>
</section>